tap 'caskroom/cask'

install 'axel'
install 'cask'
install 'diff-so-fancy'
install 'gettext'
install 'emacs'
install 'git'
install 'mas'
install 'node'
install 'openssl'
install 'python3'
install 'readline'
install 'speedtest-cli'
install 'sqlite'
install 'trash'
install 'zsh-completions'

cask 'atom'
cask 'caffeine'
cask 'google-chrome'
cask 'iterm2'
cask 'java'
cask 'nvalt'
cask 'vlc'
